#!/usr/bin/env node
// Issue a signed Deja license key.
// Reads private key from ~/.deja/keys/private.pem (generated by gen-keys.mjs).
//
// Usage:
//   node scripts/issue-license.mjs --email user@example.com --tier pro --days 365
//   node scripts/issue-license.mjs --email team@co.com --tier team --days 730

import { createSign } from "crypto";
import { readFileSync, existsSync } from "fs";
import { join } from "path";
import { homedir } from "os";

// --- parse args ---
const args = process.argv.slice(2);
function getArg(name) {
  const i = args.indexOf(`--${name}`);
  return i !== -1 ? args[i + 1] : null;
}

const email = getArg("email");
const tier = getArg("tier") ?? "pro";
const days = parseInt(getArg("days") ?? "365", 10);

if (!email) {
  console.error("Usage: node scripts/issue-license.mjs --email <email> [--tier pro|team] [--days 365]");
  process.exit(1);
}
if (!["pro", "team"].includes(tier)) {
  console.error(`Invalid tier: ${tier}. Must be "pro" or "team".`);
  process.exit(1);
}

// --- load private key ---
const PRIVATE_KEY_PATH = join(homedir(), ".deja", "keys", "private.pem");
if (!existsSync(PRIVATE_KEY_PATH)) {
  console.error(`Private key not found: ${PRIVATE_KEY_PATH}`);
  console.error("Run: node scripts/gen-keys.mjs first.");
  process.exit(1);
}
const privateKey = readFileSync(PRIVATE_KEY_PATH, "utf-8");

// --- build payload ---
const payload = {
  v: 1,
  email,
  expiry: Date.now() + days * 24 * 60 * 60 * 1000,
  tier,
};

function b64urlEncode(buf) {
  return buf.toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}

const payloadB64 = b64urlEncode(Buffer.from(JSON.stringify(payload), "utf-8"));

// --- sign ---
const signer = createSign("SHA256");
signer.update(payloadB64);
const sigBuf = signer.sign(privateKey);
const sigB64 = b64urlEncode(sigBuf);

const licenseKey = `DEJA-${payloadB64}.${sigB64}`;

// --- output ---
const expiryDate = new Date(payload.expiry).toISOString().slice(0, 10);
console.log(`License Key for ${email} (${tier}, expires ${expiryDate}):`);
console.log();
console.log(licenseKey);
console.log();
console.log(`Activate with: deja license:activate ${licenseKey}`);
